version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/setup
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/test
    schedule:
      interval: daily
    labels:
      - dependencies
