version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/setup
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/test
    schedule:
      interval: daily
    labels:
      - dependencies
