name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:

    - name: Set up Ruby
      uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # pinned to version v1.191.0
      with:
        ruby-version: '3.1.0'
        bundler-cache: true
        cache-version: 1

    - name: Setup Xcode
      uses: mxcl/xcodebuild@6e60022a0cbe8c89278be2dd1773a2f68e7c5c87
      with:
        xcode: ${{ inputs.xcode }}
        action: none
