name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  ruby:
    description: The version of Ruby to use
    required: true

  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@90be1154f987f4dc0fe0dd0feedac9e473aa4ba8 # pin@v1.286.0
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: 1

    - name: Setup Xcode
      uses: mxcl/xcodebuild@d3ee9b419c1be9a988086c58fe0988f32d99cfc5 # pin@v3.6.0
      with:
        xcode: ${{ inputs.xcode }}
        action: none
        verbosity: xcbeautify
