name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  ruby:
    description: The version of Ruby to use
    required: true

  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@0ecad18fe538ef70f6b82773daecc6af1a7fe58a # pin@v1.252.0
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: 1

    - name: Setup Xcode
      uses: mxcl/xcodebuild@e366f14791346edb74397fe9a762ccee86eddc06 # pin@v3.5.1
      with:
        xcode: ${{ inputs.xcode }}
        action: none
        verbosity: xcbeautify
