name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  ruby:
    description: The version of Ruby to use
    required: true

  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@922ebc4c5262cd14e07bb0e1db020984b6c064fe # pin@v1.226.0
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: 1

    - name: Setup Xcode
      uses: mxcl/xcodebuild@2cf0ec52b855fa777531c5c89b714caa7a3abd5e # pin@v3.4.0
      with:
        xcode: ${{ inputs.xcode }}
        action: none
        verbosity: xcbeautify
