opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - JWTDecode
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 500
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
type_name:
  min_length: 3 # only warning
  excluded: # No regex support available for this
    - _JWT
identifier_name:
  min_length: # only min_length
    warning: 3 # only error
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
