#!/bin/bash

IOS_DESTINATION="'platform=iOS Simulator,name=$IOS_DESTINATION_SIMULATOR_NAME,OS=$IOS_DESTINATION_VERSION'"

if [ -z "$OSX_DESTINATION_ARCH" ]
then
  OSX_DESTINATION="'platform=OS X'"
else
  OSX_DESTINATION="'platform=OS X,arch=$OSX_DESTINATION_ARCH'"
fi

scheme_destination ()
{
  shopt -s nocasematch

  case "$1" in
  *iOS) 
    destination=$IOS_DESTINATION
    ;;
  *OSX) 
    destination=$OSX_DESTINATION
    ;;
  *macOS) 
    destination=$OSX_DESTINATION
    ;;
  *tvOS) 
    destination="'platform=tvOS Simulator,name=Apple TV 1080p'"
    ;;  
  *) 
    destination=$IOS_DESTINATION
    ;;
  esac

  echo $destination
}