#!/bin/bash

if [ ! -f .carthage_cache.yml ]
then
  echo ""
  echo " → Generating .carthage_cache.yml file"
  echo ""
  bundle exec carthage_cache config
fi

echo ""
echo " → Configuring .travis.yml"
echo ""
script/common/configure_carthage_cache $1
