#!/bin/bash

set -e

source script/.env

if [ -f Cartfile ] && type carthage > /dev/null
then
  carthage_cmd="carthage update --platform ios"
  if [ "$USE_SSH" == "true" ]
  then
    carthage_cmd="$carthage_cmd --use-ssh"
  fi
  if [ "$USE_SUBMODULES" == "true" ]
  then
    carthage_cmd="$carthage_cmd --use-submodules --no-build"
  fi
  eval $carthage_cmd
elif [ -f Podfile ]
then
  if type bundle > /dev/null && bundle show pod > /dev/null
  then
    bundle exec pod update
  else
    pod update
  fi
fi
