#!/bin/bash
source script/common/carthage

if [ -z $REQUIRED_CARTHAGE_VERSION ]
then
  echo "Enter the version of Carthage you want to install:"
  read REQUIRED_CARTHAGE_VERSION
fi
force_install_carthage
