name: SCA

on:
  push:
    branches:
    - "**"

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=README.md"
    secrets: inherit
